
services:
    # default configuration for services in *this* file
    _defaults:
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        autowire: true      # Automatically injects dependencies in your services.

    # makes bundle classes available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Catalog\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Resources/'
            - '../../*Bundle.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Catalog\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones